trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  resourceGroupName: 'myResourceGroup'
  location: 'eastus'
  storageAccountName: 'mystorageacct1234'  # lowercase, unique
  sku: 'Standard_LRS'
  kind: 'StorageV2'

stages:
- stage: CreateStorageAccount
  displayName: 'Create Azure Storage Account'
  jobs:
  - job: CreateStorage
    displayName: 'Azure CLI Job - Create Storage Account'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'mydevops'  # Replace with your actual service connection
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Creating storage account: $env:STORAGEACCOUNTNAME in resource group: $env:RESOURCEGROUPNAME"

          # Check and create resource group if needed
          $rgExists = az group exists --name $env:RESOURCEGROUPNAME
          if ($rgExists -eq 'false') {
            Write-Host "Resource group not found. Creating resource group: $env:RESOURCEGROUPNAME"
            az group create --name $env:RESOURCEGROUPNAME --location $env:LOCATION
          }

          # Create the storage account
          az storage account create `
            --name $env:STORAGEACCOUNTNAME `
            --resource-group $env:RESOURCEGROUPNAME `
            --location $env:LOCATION `
            --sku $env:SKU `
            --kind $env:KIND `
            --allow-blob-public-access false

          Write-Host "✅ Storage account $env:STORAGEACCOUNTNAME created successfully!"
      env:
        RESOURCEGROUPNAME: $(resourceGroupName)
        LOCATION: $(location)
        STORAGEACCOUNTNAME: $(storageAccountName)
        SKU: $(sku)
        KIND: $(kind)
      displayName: 'Run Azure CLI to Create Storage Account'
