trigger:
- main

pool:
  vmImage: 'windows-latest'  # Uses a Microsoft-hosted Windows agent

variables:
  resourceGroupName: 'myResourceGroup'
  location: 'eastus'

stages:
- stage: CreateResourceGroup
  displayName: 'Create Resource Group in Azure'
  jobs:
  - job: CreateRG
    displayName: 'Azure CLI Job - Create Resource Group'
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'mydevops'  # Replace this with your actual service connection
        scriptType: 'ps'  # PowerShell script on Windows agent
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Creating resource group: $env:RESOURCEGROUPNAME in $env:LOCATION"
          az group create `
            --name $env:RESOURCEGROUPNAME `
            --location $env:LOCATION
      env:
        RESOURCEGROUPNAME: $(resourceGroupName)
        LOCATION: $(location)
      displayName: 'Run Azure CLI to Create Resource Group'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'mydevops'  # Replace with your actual Azure service connection name
        scriptType: 'ps'  # PowerShell script
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Creating storage account: $env:STORAGEACCOUNTNAME in resource group: $env:RESOURCEGROUPNAME"
          
          # Check if resource group exists
          $rgExists = az group exists --name $env:RESOURCEGROUPNAME
          if ($rgExists -eq 'false') {
            Write-Host "Resource group not found. Creating resource group: $env:RESOURCEGROUPNAME"
            az group create --name $env:RESOURCEGROUPNAME --location $env:LOCATION
          }

          # Create storage account
          az storage account create `
            --name $env:STORAGEACCOUNTNAME `
            --resource-group $env:RESOURCEGROUPNAME `
            --location $env:LOCATION `
            --sku $env:SKU `
            --kind $env:KIND `
            --allow-blob-public-access false

          Write-Host "✅ Storage account $env:STORAGEACCOUNTNAME created successfully!"
      env:
        RESOURCEGROUPNAME: $(resourceGroupName)
        LOCATION: $(location)
        STORAGEACCOUNTNAME: $(storageAccountName)
        SKU: $(sku)
        KIND: $(kind)
      displayName: 'Run Azure CLI to Create Storage Account'
